### PR TITLE
Issue #167: 32bit build fails

### LINKED ISSUE #167: Build in 32 bit environment fails
When crosscompiling for a 32 bit environment, I get the following two issues:
```
.../src/github.com/gopcua/opcua/ua/node_id.go:133:22: constant 4294967295 overflows int
.../src/github.com/gopcua/opcua/ua/node_id.go:250:10: constant 4294967295 overflows int
```

The first issue arises since `strconv.Atoi` a few lines earlier returns an `int` which in my system is 32 bit and thus cannot be compared to an `uint32`. Using `ParseUint` instead solved the problem:
```go
id, err := strconv.ParseUint(idval[2:], 10, 32)
```

The second issue is similar, but for that I made an uglier solution to get it to work by changing the input argument of SetIntID to an `uint32` and fiddling a bit with casting etc in the code below.

This relates to commit b9119dc of `ua/node_id.go`

### PR DESCRIPTION
**Pull request by magiconair**
Fix code for 32 and 64 bit platforms

Fixes #167

### CODE REVIEW

File: ua/node_id.go [hunk 1]
```diff
@@ -224,30 +224,30 @@ func (n *NodeID) SetNamespace(v int) error {
...
 }
 
 // SetIntID sets the identifier value for two byte, four byte and
 // numeric node ids. It returns an error for other types.
-func (n *NodeID) SetIntID(v int) error {
+func (n *NodeID) SetIntID(v uint32) error {
 	switch n.Type() {
 	case NodeIDTypeTwoByte:
-		if max := math.MaxUint8; v < 0 || v > max {
+		if max := uint32(math.MaxUint8); v < 0 || v > max {
```
Comment (golangcibot) [inline ua/node_id.go]: SA4003: unsigned values are never < 0 (from `staticcheck`)

File: ua/node_id.go [hunk 2]
```diff
@@ -224,30 +224,30 @@ func (n *NodeID) SetNamespace(v int) error {
...
 			return fmt.Errorf("out of range [0..%d]: %d", max, v)
 		}
 		n.nid = uint32(v)
 		return nil
 
 	case NodeIDTypeFourByte:
-		if max := math.MaxUint16; v < 0 || v > max {
+		if max := uint32(math.MaxUint16); v < 0 || v > max {
```
Comment (golangcibot) [inline ua/node_id.go]: SA4003: unsigned values are never < 0 (from `staticcheck`)

File: ua/node_id.go [hunk 3]
```diff
@@ -224,30 +224,30 @@ func (n *NodeID) SetNamespace(v int) error {
...
 			return fmt.Errorf("out of range [0..%d]: %d", max, v)
 		}
 		n.nid = uint32(v)
 		return nil
 
 	case NodeIDTypeNumeric:
-		if max := math.MaxUint32; v < 0 || v > max {
+		if max := uint32(math.MaxUint32); v < 0 || v > max {
```
Comment (golangcibot) [inline ua/node_id.go]: SA4003: unsigned values are never < 0 (from `staticcheck`)
