### PR TITLE
Fix races to c.Session() and c.SecureChannel()

### LINKED ISSUE #640: Panic in secure_channel.go
Hello,
I got a panic when calling `ReadWithContext()`.
I cannot reproduce the error, I was calling the function a huge number of times before and without any change in the setup I randomly got this panic once.

Do you have an idea what could be the reason for it and how to prevent it?

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x7eafef]
> 
> goroutine 63 [running]:
> github.com/gopcua/opcua/uasc.(*SecureChannel).SendRequestWithTimeoutWithContext(0x0, {0xc63d20, 0xc00003c058}, {0xc618d8, 0xc000410360}, 0xa053c0?, 0xc0004dda80?, 0x10bd360?)
> 	github.com/gopcua/opcua@v0.3.11/uasc/secure_channel.go:748 +0x4f
> github.com/gopcua/opcua.(*Client).sendWithTimeout(0x108c8a0?, {0xc63d20?, 0xc00003c058?}, {0xc618d8?, 0xc000410360?}, 0xc0004ddaf0?, 0x40f9a7?)
> 	github.com/gopcua/opcua@v0.3.11/client.go:942 +0x136
> github.com/gopcua/opcua.(*Client).SendWithContext(0xc00058c690, {0xc63d20, 0xc00003c058}, {0xc618d8, 0xc000410360}, 0xa9a420?)
> 	github.com/gopcua/opcua@v0.3.11/client.go:925 +0x91
> github.com/gopcua/opcua.(*Client).ReadWithContext(0xa320c0?, {0xc63d20, 0xc00003c058}, 0xc0003e3b00)
> 	github.com/gopcua/opcua@v0.3.11/client.go:1014 +0x29c

### PR DESCRIPTION
**Pull request by magiconair**
In these cases the method calls c.SecureChannel and/or c.Session multiple times and during a re-connect the returned value can change. This patch addresses this by storing the returned value in a local variable.

Fixes #640

### CODE REVIEW

**Comment by magiconair** [comment]
@bitomaxsp could you have a look please?

**Review by bitomaxsp — APPROVED** [review]

File: client.go [hunk 1]
```diff
@@ -727,7 +725,8 @@ func (c *Client) CreateSession(cfg *uasc.SessionConfig) (*Session, error) {
 
 // Note: Starting with v0.5 this method is superseded by the non 'WithContext' method.
 func (c *Client) CreateSessionWithContext(ctx context.Context, cfg *uasc.SessionConfig) (*Session, error) {
-	if c.SecureChannel() == nil {
+	sc := c.SecureChannel()
```
Comment (bitomaxsp) [inline client.go:732]: Do you think it make sense to have a comment saying why we capture it?
might be not that obvious

Comment (magiconair) [reply client.go:732]: Good point. I can add a comment to the method signature.
