### PR TITLE
Issue #762: Remove calls to log.Fatal

### LINKED ISSUE #762: Very dangerous log.Fatal called in several places
(using v6.0.2)
We are about to use this in production and we noticed that when passing an invalid certificate it panics. This can cause unexpected failures at runtimes, and i saw that https://github.com/gopcua/opcua/issues/616 was marked as closed but it does not seem to be.

There are three `log.Fatal` in the codebase:
- `config.go` line 325: "Failed to parse certificate"
- `server.go` line 112 and line 151

I wonder why the error cannot bubble up to the `NewClient` because that now returns an error. 

Are we missing something? Thanks in advance

### PR DESCRIPTION
**Pull request by danomagnum**
The function that used log.Fatal in config.go isn't exported and is only called by functions that return errors so I added an error return then pass it up.

The first log.Fatal in server.go followed the same approach as #616 to delay the error till the start() is called on the server.

The second log.Fatal in server.go should never be possible, so I changed it to a panic (which should never happen).

Fixes #762

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -108,11 +108,15 @@ func New(opts ...Option) *Server {
 	for _, opt := range opts {
 		opt(cfg)
 	}
+	url := ""
 	if len(cfg.endpoints) == 0 {
-		log.Fatalf("No endpoints defined!")
+		log.Printf("No endpoints defined!")
```
Comment (magiconair) [inline server/server.go]: I'd remove the log statement here. Either we validate in the `New` function and return an error or we check later. If we don't want to change the signature of `New` then we check later and you have a check for that.

**Review by magiconair — CHANGES_REQUESTED** [review]
Other than that LGTM

**Comment by magiconair** [comment]
LGTM

**Review by magiconair — APPROVED** [review]

**Comment by danomagnum** [comment]
@magiconair 

Did you see what happened with the checks on this?  It failed the first time (couldn't open port 4840 in one of the conn_test tests).  It does pass on my machine, so I pushed an empty commit and when it ran again, it passed.  Some kind of race condition must exist in terms of one test closing the port fast enough before another can open it?  Pretty strange.

On the python integration tests I've started getting a different error sometimes too.  I'm sure it's something with how my network is setup, but I'm not 100% sure why it doesn't try to go out the gateway anyway.

```
=== RUN   TestClientTimeoutViaOptions
Endpoints other than open requested but private key and certificate are not set.
Listening on 0.0.0.0:4840
    timeout_test.go:55: 
                Error Trace:    /home/dan/programs/opcua/tests/python/timeout_test.go:55
                                                        /home/dan/programs/opcua/tests/python/timeout_test.go:28
                Error:          got %#v, wanted net.timeoutError
                Test:           TestClientTimeoutViaOptions
                Messages:       connect: network is unreachable
--- FAIL: TestClientTimeoutViaOptions (1.45s)
```

**Comment by magiconair** [comment]
I've seen this and it happens sporadically but not often enough for me to be concerned. Would be great to understand why though. 

Released as v0.6.3

**Comment by magiconair** [comment]
@danomagnum I wonder where all the thumbs-up on the issue came from. People from your company? If this was such an issue why didn't anyone raise this sooner.

**Comment by danomagnum** [comment]
@magiconair I don't know.  Not sure who any of the people are.  I saw the issue about log.fatal come in and it involved the server so I went ahead and fixed it.  That issue got a bunch of attention really quickly as well.  Maybe all those people are at the same company?
