### PR TITLE
check for invalid/duplicate subscription id

### LINKED ISSUE #254: Prosys Simulation Server returns duplicate subscription IDs
When creating multiple subscriptions in quick succession, I have seen the same sub ID come back. This causes an overwrite here: https://github.com/gopcua/opcua/blob/v0.1.4/client.go#L556
Which then causes data change notifications to be dispatched to the wrong handler.

Quick fix is to check for an existing Subscription ID, and return an error. But since the subscription has already been created on the server, do we need to cleanup?

Or is this technically a valid response?

Log: [prosys.log](https://github.com/gopcua/opcua/files/3461440/prosys.log)

You can see two `CreateSubscriptionResponse` come back with `SubscriptionId=28`

image

### PR DESCRIPTION
**Pull request by kung-foo**
fixes #254

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -553,6 +553,12 @@ func (c *Client) Subscribe(params *SubscriptionParameters) (*Subscription, error
 		c,
 	}
 	c.subMux.Lock()
+	if _, ok := c.subscriptions[sub.SubscriptionID]; ok {
```
Comment (magiconair) [inline client.go]: `SubscriptionID` is an `IntegerId` (Part 4, 7.14) which cannot be zero. So we should also check for `0` and I think you can simplify the check to 

```go
if c.subscriptions[sub.SubscriptionID] != nil {
	c.subMux.Unlock()
	return sub, ua.StatusBadSubscriptionIDInvalid
}
```

File: client.go [hunk 2]
```diff
@@ -553,6 +553,12 @@ func (c *Client) Subscribe(params *SubscriptionParameters) (*Subscription, error
 		c,
 	}
 	c.subMux.Lock()
+	if sub.SubscriptionID == 0 || c.subscriptions[sub.SubscriptionID] != nil {
```
Comment (magiconair) [inline client.go:556]: We could check the subscription id right after the `StatusOK` check and shouldn't you return `nil` instead of `sub` on error?

Comment (kung-foo) [reply client.go:556]: Yeah, I thought about returning `nil`, but _technically_ subscription resources _have_ been created on the server. But realistically, it would be hard to cleanup because I think most operations use the ID. I usually think of `nil` as indicating that nothing was created.

Comment (magiconair) [reply client.go:556]: The clean-up will never be called b/c the caller checks the error and moves on unless we specifically document that behavior. Then there is nothing useful the caller can do with this. If there is useful cleanup you can do in the client then you should do it here. However, the whole point is that this checks for bugs and edge cases in the server. Lets just return `nil` here unless I'm missing smth substantial.

**Comment by magiconair** [comment]
LGTM
